name: tests

on:
  pull_request:
    branches:
      - master

jobs:
  Unit-test:
  name: Run unit tests on PR in master
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4
  
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Run Unit tests
      run: ./gradlew test
